# Generated by Django 6.0.6 on 2026-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_tersedia', models.BooleanField(default=True)),
            ],
        ),
    ]
