# Generated by Django 6.0.6 on 2026-06-10 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('siap', 'Siap Diambil')], default='menunggu', max_length=20)),
                ('nomor_antrean', models.IntegerField(default=0)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=1)),
                ('sub_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.pesanan')),
            ],
        ),
    ]
